### PR TITLE
Ignore vLLM test

### PR DESCRIPTION
**Pull request by nihalnayak**
PR to Ignore vLLM test. Please double-check if this ignores the test for vLLM.

### CODE REVIEW

**Comment by vinid** [comment]
Hello and thanks for the fix!

I wonder if we should just maybe install vllm for the tests?

**Comment by nihalnayak** [comment]
Good question. I think we can install vllm in the workflow. But, I'm not sure if we can run the `test_primitives()` as it requires llama3-8b-instruct. Smaller models don't really work.

**Comment by vinid** [comment]
makes sense! @mertyg I'd probably just merge and skip the tests, wdyt?

**Review by mertyg — APPROVED** [review]
thanks @nihalnayak for bearing with us!

**Pull request merged**
