### PR TITLE
Adding groq support

### PR DESCRIPTION
**Pull request by vaibhavnayel**
This is a small PR adding support from Groq LLMs for faster execution.
- Added a new file `textgrad/engine/groq.py` based on `textgrad/engine/openai.py`
- Modified `textgrad/engine/__init__.py` to parse models containing `groq` in the name
- Tested the change on `textgrad/examples/notebooks/Tutorial-Test-Time-Loss-for-Code.ipynb`, `textgrad/examples/notebooks/Tutorial-Primitives.ipynb` and the 
- Note: Groq does not currently support multimodal inputs and will raise an error if multimodal inputs are passed
Hope this helps with faster training times!

### CODE REVIEW

**Comment by vinid** [comment]
Thank you for this!

Is groq API compatible with the chatgpt API? if so, is there any chance that we avoid reimplementing the generate methods by inheriting from the ChatGPT wrapper and changing the client from OpenAI to Groq? 

I'd assume that if the API is compatible, swapping the client would work seamlessly, is this reasoning correct?

**Comment by vaibhavnayel** [comment]
Thanks for your reponse @vinid. Yes, groq API is indeed designed to be [compatible](https://console.groq.com/docs/openai) with OpenAI. The catch is that it does not support multimodal inputs. 
What you are saying sounds like a better solution than duplicating the code. I will make a fix to this PR soon.

**Comment by vaibhavnayel** [comment]
@vinid I've refactored the `ChatGroq` class to inherit from `ChatOpenAI`. Does this look okay?

**Comment by vinid** [comment]
Not yet! will do it soon! 
In the meantime, I saw a breakpoint in the __init__, could you remove that?

thanks!

**Comment by vinid** [comment]
thank you for your contribution!

**Review by vinid — APPROVED** [review]

**Pull request merged**
