### PR TITLE
Feature/bedrock

### PR DESCRIPTION
**Pull request by kristoftabori**
New Engine with basic unit tests added to interact with AWS Bedrock. The engine needs to be initialized with a `botocore` `BaseClient` for authentication/authorization purposes.
It closes the issue [Bedrock #105](https://github.com/zou-group/textgrad/issues/105).

### CODE REVIEW

**Comment by vinid** [comment]
Hello and thanks for this! We have an upcoming PR (#120) that introduces litellm as an engine. This should hopefully cover most models (bedrock too) with one single implementation!

Let us know if you think this makes sense or if you think we should probably keep bedrock's client separated from the rest!

**Comment by kristoftabori** [comment]
hi Federico, thank you for pointing towards the LiteLLM direction. I think this PR's implementation gives an intuitive out-of-the-box experience if the user has already a `boto`  session running. It's a good default for people working in teams where only Bedrock-provided models are available.
I would vote for having this sperately for the time being.

**Comment by vinid** [comment]
sounds good, can you make 

```
langchain>=0.3.0
langchain-aws>=0.2.1
```
optional like in [grok](https://github.com/zou-group/textgrad/blob/main/textgrad/engine/groq.py)? we can merge this after that

**Comment by kristoftabori** [comment]
> sounds good, can you make
> 
> ```
> langchain>=0.3.0
> langchain-aws>=0.2.1
> ```
> 
> optional like in [grok](https://github.com/zou-group/textgrad/blob/main/textgrad/engine/groq.py)? we can merge this after that

Thank you for the insight. I've just implemented it, please take a look.

**Review by vinid — APPROVED** [review]

**Comment by vinid** [comment]
thanks again for this!

**Comment by yzjing** [comment]
Hi, thank you for adding this support! Is there an usage example? I've searched the repo but have not found out how to use this engine.

**Pull request merged**
